<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Com_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function update_commission($id, $params)
    {
        $this->db->where('comId',$id);
        $this->db->update('commissions',$params);
    }

    public function get_commission($params)
    {
        return $this->db->get_where('commissions',$params)->row_array();
    }
    

}
