<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Coup_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function add_coupon($params)
    {
    	$this->db->insert('coupons',$params);
    	return $this->db->insert_id();
    }

    public function get_coupon_duplicate($params)
    {
        $this->db->where('coupCode',$params['coupCode']);
        $query=$this->db->get('coupons');
        $c=$query->num_rows(); 
        if($c>0){
            return true;
        }
        else{
            return false; 
        }
    }

    function get_all_coupons()
    {
        return $this->db->get('coupons')->result_array();
    }

    function update_status($id, $params)
    {
        $this->db->where('coupId',$id);
        $this->db->update('coupons',$params);

        if($this->db->affected_rows() == '1'){
            return true;
        }else{
            return false;
        }
    }

    function update_coupon($id, $params)
    {
        $this->db->where('coupId',$id);
        $this->db->update('coupons',$params);

    }
    

}
