<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Mnco_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function add_country($params)
    {
    	$this->db->insert('multinational_country',$params);
    	return $this->db->insert_id();
    }

    public function get_mnco_duplicate($params)
    {
        $this->db->where('mncoSName',$params['mncoSName']);
        $query=$this->db->get('multinational_country');
        $c=$query->num_rows(); 
        if($c>0){
            return true;
        }
        else{
            return false; 
        }
    }

    function get_all_mnco()
    {
        return $this->db->get('multinational_country')->result_array();
    }

    function update_status($id, $params)
    {
        $this->db->where('mncoId',$id);
        $this->db->update('multinational_country',$params);

        if($this->db->affected_rows() == '1'){
            return true;
        }else{
            return false;
        }
    }

    function update_country($id, $params)
    {
        $this->db->where('mncoId',$id);
        $this->db->update('multinational_country',$params);
    }
    

}
