<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Mncu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function add_currency($params)
    {
    	$this->db->insert('multinational_currency',$params);
    	return $this->db->insert_id();
    }

    public function get_mncu_duplicate($params)
    {
        $this->db->where('mncuSName',$params['mncuSName']);
        $query=$this->db->get('multinational_currency');
        $c=$query->num_rows(); 
        if($c>0){
            return true;
        }
        else{
            return false; 
        }
    }

    function get_all_mncu()
    {
        return $this->db->get('multinational_currency')->result_array();
    }

    function update_status($id, $params)
    {
        $this->db->where('mncuId',$id);
        $this->db->update('multinational_currency',$params);

        if($this->db->affected_rows() == '1'){
            return true;
        }else{
            return false;
        }
    }

    function update_currency($id, $params)
    {
        $this->db->where('mncuId',$id);
        $this->db->update('multinational_currency',$params);
    }
    

}
