<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Mnlang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function add_language($params)
    {
    	$this->db->insert('multinational_language',$params);
    	return $this->db->insert_id();
    }

    public function get_mnlang_duplicate($params)
    {
        $this->db->where('mnlangSName',$params['mnlangSName']);
        $query=$this->db->get('multinational_language');
        $c=$query->num_rows(); 
        if($c>0){
            return true;
        }
        else{
            return false; 
        }
    }

    function get_all_mnlang()
    {
        return $this->db->get('multinational_language')->result_array();
    }

    function get_all_active_mnlang()
    {
        $this->db->where('mnlangStatus','active');
        $query=$this->db->get('multinational_language');
        return $query->result_array();
    }

    function update_status($id, $params)
    {
        $this->db->where('mnlangId',$id);
        $this->db->update('multinational_language',$params);

        if($this->db->affected_rows() == '1'){
            return true;
        }else{
            return false;
        }
    }

    function update_language($id, $params)
    {
        $this->db->where('mnlangId',$id);
        $this->db->update('multinational_language',$params);
    }
    

}
