<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Pcat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function add_category($params)
    {
    	$this->db->insert('product_categories',$params);
    	return $this->db->insert_id();
    }

    public function get_pcat_duplicate($params)
    {
        $this->db->where('pcatName',$params['pcatName']);
        $query=$this->db->get('product_categories');
        $c=$query->num_rows(); 
        if($c>0){
            return true;
        }
        else{
            return false; 
        }
    }

    function get_all_pcat()
    {
        return $this->db->get('product_categories')->result_array();
    }

    function get_all_active_pcat()
    {
        $this->db->where('pcatStatus','active');
        $query=$this->db->get('product_categories');
        return $query->result_array();
    }

    function update_status($id, $params)
    {
        $this->db->where('pcatId',$id);
        $this->db->update('product_categories',$params);

        if($this->db->affected_rows() == '1'){
            return true;
        }else{
            return false;
        }
    }

    function update_category($id, $params)
    {
        $this->db->where('pcatId',$id);
        $this->db->update('product_categories',$params);
    }


    public function get_image_name($params)
    {
        return $this->db->get_where('product_categories',$params)->row_array();
    }
    

}
